name: Arduino CI
on: [push, pull_request]

env:
  ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: http://arduino.esp8266.com/stable/package_esp8266com_index.json

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP8266
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Install AirGradient Library
        run: |
          arduino-cli lib install "AirGradient Air Quality Sensor"

      - name: Install Sensirion Core
        run: |
          arduino-cli lib install "Sensirion Core"
          # https://github.com/Sensirion/arduino-core/

      - name: Install Sensirion I2C SGP41
        run: |
          arduino-cli lib install "Sensirion I2C SGP41"
          # https://github.com/Sensirion/arduino-i2c-sgp41

      - name: Install Sensirion Gas Index Algorithm
        run: |
          arduino-cli lib install "Sensirion Gas Index Algorithm"
          # https://github.com/Sensirion/arduino-gas-index-algorithm 

      - name: Install U8g2lib display library
        run: |
          arduino-cli lib install "U8g2"
          # https://github.com/olikraus/u8g2

      - name: Compile Sketch
        run: arduino-cli compile --fqbn esp8266:esp8266:d1_mini ./AirGradient-DIY
